### ISSUE TITLE
Be able to put middleware in processing the AST

### ISSUE THREAD

**Issue by Vaelatern** [bobertlo/vmd#17]
Howdy!

I think you've got the only golang library out there that supports going from markdown to AST and then back to Markdown.

What do you think about allowing AST manipulations between parse and render? The idea being I pass in a function as a callback, or I have ownership of the blackfriday/v2 AST between parse and render?

Would basically mean adding a wrapper around the internal Render structure. I could do it today if instead of being in internal/ it was in pkg...

What do you think?

**Comment by Vaelatern** [comment]
Turns out I could import  https://github.com/jsternberg/markdownfmt/blob/c2a5702991e37f837f84104a79fa48fd215d0458/markdown/main.go today

**Comment by bobertlo** [comment]
I remember being warned by a Mr Aldridge to place anything I do not want to maintain publicly in `internal/` while starting this project :)

I can't remember exactly what but it seems like there were some serious issues with blackfriday to the point that I would rewrite from a different backend were I to do any serious work on this project.  Yes, that other project works pretty well but was not foolish enough to attempt to format to a set length column, which turned out to be a rather unpopular feature.

**Comment by Vaelatern** [comment]
I imported github.com/jsternberg/markdownfmt/markdown and used it as here: https://github.com/Vaelatern/mdbook-d2-go/blob/ace29af66b63df6f54abc66973104b49bb0d6c4f/main.go#L186-L192 to go from blackfriday's AST back to markdown

also pictured, an example of mutating an AST before returning it to markdown.

**Comment by Vaelatern** [comment]
I don't think blackfriday's API was bad.

**Comment by bobertlo** [comment]
> I don't think blackfriday's API was bad.

Yeah, the only complaint is an obscure bug making me vendor things to get the current functionality, and other elements missing or incorrect in the AST blocking other feature requests. Upstream does not seem interested since the AST is not designed for public consumption and the bugs do not affect their use case.

**Comment by Vaelatern** [comment]
Shame when Rust has a `pullmark` crate that does this easily, but I like using Go.
