### ISSUE TITLE
Text between unescaped angle brackets is silently deleted

### ISSUE THREAD

**Issue by mmnmnnmnmm** [bobertlo/vmd#3]
For instance running vmd over this example results in a empty file:

    <word
    <word>
    <This will be deleted>
    <This will also be deleted
    >

I think that it is unexpected and that perhaps a warning should be emitted.

**Comment by bobertlo** [comment]
Angle brackets are for links, whose descriptive text is the same as the destination, or html blocks. Since VMD does not allow embedded html, this input is invalid it is being discarded.

This is what blackfriday is emitting:

```
Document
  Paragraph
    Text ""
    HTMLSpan
    Text "\n"
    HTMLSpan
    Text "\n"
    HTMLSpan
```

As much as I would like to specifically fail on invalid input like this, silently removing it is an error in itself in the intended use case. I will think about adding a warning, but that is why it is being deleted.

**Comment by bobertlo** [comment]
I added a warning when unsupported node types are ignored.
