### ISSUE TITLE
backslashes are deleted

### ISSUE THREAD

**Issue by Wychmire** [bobertlo/vmd#8]
Running vmd over this:
```
${EDITOR} /etc/xbps.d/\*.conf ${EDITOR} /usr/share/xbps.d/\*.conf
${EDITOR} /etc/xbps.d/\*.conf or ${EDITOR} /usr/share/xbps.d/\*.conf

paclist \<repo\>
```

Results in this:
```
${EDITOR} /etc/xbps.d/*.conf ${EDITOR} /usr/share/xbps.d/*.conf
${EDITOR} /etc/xbps.d/*.conf or ${EDITOR} /usr/share/xbps.d/*.conf

paclist <repo>
```
In the first case the text in between the asterisks becomes italic (as opposed to representing multiple files), and in the second it makes vmd complain about it being a "tag": `error: Unsupported node type HTMLSpan ignored`

**Comment by bobertlo** [comment]
Oof, I'll look into this. If I knew how weird this front-end was I might have just written my own!

**Comment by bobertlo** [comment]
Ok. I have tested this and they are consumed in plain text because that's sort of how backslashes are supposed to work. If you did a double backslash it would emit a backslash, but then formatting again would remove it.

I do not see a strong use case for backslash characters outside of literal quotes. I have tested both inline and block quotes and backslashes are treated literally there.

I am going to close this because a) there is no way to fix this without going upstream and b) I don't view this as fully being a 'bug'.

**Comment by Wychmire** [comment]
Fair enough I guess. Anywhere asterisks or angle brackets are required I guess I'll just use the appropriate html entity.

**Comment by bobertlo** [comment]
Well in the case of the void docs anything that requires those types of symbols should be inside a quote anyways. Plain text areas are reserved for plain English text. Hint: html tags don't pass the linter either.

**Comment by Wychmire** [comment]
The reason I discovered and am bringing this up is because of [void-docs/pull/111](https://github.com/void-linux/void-docs/pull/111). Though it's probably better to be discussing this at that PR, should I be wrapping the individual commands in quotes then? (Also, do you mean single, double quotes or grave accents?)

**Comment by bobertlo** [comment]
Just to be clear when I say quotes I mean either `inline blocks` or:

```
Blocks like this
```

The way I approach it anything not inside one of those elements should be plain language not needing things like backslashes and symbols.
